# region server
server.servlet.context-path=/pine
server.port=8080
server.tomcat.accept-count=1000
server.tomcat.max-connections=10000
server.tomcat.threads.min-spare=100
server.tomcat.threads.max=800
# endregion server

# region spring
spring.jackson.date-format = yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.serialization.write-dates-as-timestamps=true
spring.servlet.multipart.enabled=true
# endregion spring

# region database
database.sources.db.databaseType=kdb
database.sources.db.channel=kdbHttp
database.sources.db.innerType=MySql
database.sources.db.server=http://10.11.2.62:10081
database.sources.db.executeSqlApi=/api/execute4debug
# DB??:?????:?????
database.sources.db.dbName=db:MySql:MySql,kingDB:kingDB:HSQLDB
# endregion database

# region encrypt
encrypt.mode=base64
# endregion encrypt

# region auth
app.auth.enable=true
app.auth.iss=kingsware
app.auth.tokenExpireMinutes=120
app.auth.tokenSecret=3kj0ByucpznafmRd
app.auth.login-session-one=false
app.auth.mock-session-expire-minutes=-1
app.uniops.validate-dirs=KQoQshso6VCsqZRM2ChnfaNHj7c9u6NViQ3Q2oz+X78ljQMvesvD5i4VxnSL0i7Xhcyrk3/v+NY7uHPEsBkkjw==
# endregion auth

# region pine dev mode
app.mode.dev=false
app.file-local-to-faas=true
# endregion pine dev mode

# region file
file.base-path = upload

# region k-flow
app.k-flow.enable=true
app.k-flow.call-model=sdk
# endregion k-flow

app.ui.prefix=/pine
app.ui=webapps/pine/ui/


uniops.user=admin
uniops.pwd=WzIyNCwxMiwxNTYsMTgwLDE3MiwxNiwxNjMsMjQ1LDIzMywxNTcsNTAsMTg3LDM2LDExOSw4NiwxNzhd
uniops.server=http://10.11.2.60:8080
# ???????????????????????????application.properties???
file.write-list = png,jpg,jpeg,gif,svg,html,tif,bmp,pic,pdf,doc,docx,xls,xlsx,ppt,pptx,csv,jar,license,wps,txt,rar,zip,gz,wav,mp3,wma,aac,flac,avi,mpg,mov,mp4,pine,json,xml


