ALTER TABLE sys_api
    MODIFY COLUMN api_tags VARCHAR(255) DEFAULT NULL COMMENT '标签';

ALTER TABLE sys_logic_flow
    MODIFY COLUMN tags VARCHAR(255) DEFAULT NULL COMMENT '标签';

ALTER TABLE dev_page
    MODIFY COLUMN tags VARCHAR(255) DEFAULT NULL COMMENT '标签';
