CREATE TABLE  DEV_PINE_PLUGIN (
    ID varchar(36) NOT NULL,
    APP_ID varchar(36),
    AUTHOR varchar(50),
    ENABLE_STATUS int DEFAULT 0,
    FILE_ID varchar(36),
    NOTE clob,
    PLUGIN_NAME varchar(50),
    PLUGIN_VERSION varchar(10),
    WHEN_CREATED varchar(36),
    WHEN_MODIFIED varchar(30),
    WHO_CREATED varchar(36),
    WHO_MODIFIED varchar(36),
    PRIMARY KEY (ID)
);
COMMENT ON COLUMN DEV_PINE_PLUGIN.APP_ID IS '归属应用id';
COMMENT ON COLUMN DEV_PINE_PLUGIN.AUTHOR IS '插件作者';
COMMENT ON COLUMN DEV_PINE_PLUGIN.ENABLE_STATUS IS '是否启动';
COMMENT ON COLUMN DEV_PINE_PLUGIN.FILE_ID IS '文件id';
COMMENT ON COLUMN DEV_PINE_PLUGIN.NOTE IS '说明';
COMMENT ON COLUMN DEV_PINE_PLUGIN.PLUGIN_NAME IS '插件名称';
COMMENT ON COLUMN DEV_PINE_PLUGIN.PLUGIN_VERSION IS '插件版本号';
COMMENT ON COLUMN DEV_PINE_PLUGIN.WHEN_CREATED IS '创建时间';
COMMENT ON COLUMN DEV_PINE_PLUGIN.WHEN_MODIFIED IS '修改时间';
COMMENT ON COLUMN DEV_PINE_PLUGIN.WHO_CREATED IS '创建人';
COMMENT ON COLUMN DEV_PINE_PLUGIN.WHO_MODIFIED IS '修改人员';


CREATE TABLE  DEV_MODEL_SQL (
    ID varchar(36) NOT NULL,
    APP_ID varchar(36),
    TITLE varchar(255),
    SOURCE_NAME varchar(50),
    CONTENT clob,
    STATUS int DEFAULT 0,
    SQL_VERSION int,
    MESSAGES clob,
    IGNORE_EXCEPT int DEFAULT 1,
    EXEC_ERR_LINE int DEFAULT 0,
    EXEC_TIME varchar(20),
    EXEC_USER_ID varchar(36),
    WHEN_CREATED varchar(20),
    WHO_CREATED varchar(36),
    WHEN_MODIFIED varchar(20),
    WHO_MODIFIED varchar(36),
    PRIMARY KEY (ID)
);
COMMENT ON COLUMN DEV_MODEL_SQL.ID IS '主键';
COMMENT ON COLUMN DEV_MODEL_SQL.APP_ID IS '应用id';
COMMENT ON COLUMN DEV_MODEL_SQL.TITLE IS '标题';
COMMENT ON COLUMN DEV_MODEL_SQL.SOURCE_NAME IS '数据源';
COMMENT ON COLUMN DEV_MODEL_SQL.CONTENT IS '脚本';
COMMENT ON COLUMN DEV_MODEL_SQL.STATUS IS '执行状态 0: 未执行 1：已执行 2：执行异常';
COMMENT ON COLUMN DEV_MODEL_SQL.SQL_VERSION IS '版本号';
COMMENT ON COLUMN DEV_MODEL_SQL.MESSAGES IS '执行结果';
COMMENT ON COLUMN DEV_MODEL_SQL.IGNORE_EXCEPT IS '是否忽略错误';
COMMENT ON COLUMN DEV_MODEL_SQL.EXEC_ERR_LINE IS '错误行号';
COMMENT ON COLUMN DEV_MODEL_SQL.EXEC_TIME IS '执行时间';
COMMENT ON COLUMN DEV_MODEL_SQL.EXEC_USER_ID IS '执行人';
COMMENT ON COLUMN DEV_MODEL_SQL.WHEN_CREATED IS '创建时间';
COMMENT ON COLUMN DEV_MODEL_SQL.WHO_CREATED IS '创建人';
COMMENT ON COLUMN DEV_MODEL_SQL.WHEN_MODIFIED IS '修改时间';
COMMENT ON COLUMN DEV_MODEL_SQL.WHO_MODIFIED IS '修改人';


CREATE TABLE  DEV_DATA_SOURCE (
    ID varchar(36) NOT NULL,
    NAME varchar(100),
    WHO_CREATED varchar(36),
    WHEN_CREATED varchar(30),
    WHO_MODIFIED varchar(36),
    WHEN_MODIFIED varchar(30),
    APP_ID varchar(36),
    KDB_ID varchar(40),
    TEAM_ID varchar(36),
    DELETED int,
    PRIMARY KEY (ID)
);
COMMENT ON COLUMN DEV_DATA_SOURCE.ID IS 'ID';
COMMENT ON COLUMN DEV_DATA_SOURCE.NAME IS '数据源名称';
COMMENT ON COLUMN DEV_DATA_SOURCE.WHO_CREATED IS '创建人员';
COMMENT ON COLUMN DEV_DATA_SOURCE.WHEN_CREATED IS '创建时间';
COMMENT ON COLUMN DEV_DATA_SOURCE.WHO_MODIFIED IS '修改人员';
COMMENT ON COLUMN DEV_DATA_SOURCE.WHEN_MODIFIED IS '修改时间';
COMMENT ON COLUMN DEV_DATA_SOURCE.APP_ID IS '关联应用';
COMMENT ON COLUMN DEV_DATA_SOURCE.KDB_ID IS '在kingDB中对应的ID';
COMMENT ON COLUMN DEV_DATA_SOURCE.TEAM_ID IS '所属团队ID';
COMMENT ON COLUMN DEV_DATA_SOURCE.DELETED IS '是否已删除';


CREATE TABLE  DEV_SEARCH_HISTORY (
    ID varchar(36) NOT NULL,
    KEYWORD varchar(36) NOT NULL,
    USE_NUM int,
    DELETED int DEFAULT 0,
    PRIMARY KEY (ID)
 );
COMMENT ON COLUMN DEV_SEARCH_HISTORY.ID IS '主键';
COMMENT ON COLUMN DEV_SEARCH_HISTORY.KEYWORD IS '关键字';
COMMENT ON COLUMN DEV_SEARCH_HISTORY.USE_NUM IS '搜索次数';
COMMENT ON COLUMN DEV_SEARCH_HISTORY.DELETED IS '是否删除';


CREATE TABLE  DEV_GIT_TAG (
    ID varchar(36) NOT NULL,
    TAG varchar(255),
    REPO varchar(255),
    "RESOURCE" varchar(255),
    COMMIT_ID varchar(255),
    PUBLIC_COMMIT_IDS clob,
    NOTE clob,
    WHEN_CREATED varchar(20),
    WHO_CREATED varchar(255),
    PRIMARY KEY (ID)
);
COMMENT ON COLUMN DEV_GIT_TAG.ID IS '主键';
COMMENT ON COLUMN DEV_GIT_TAG.TAG IS '标签名称';
COMMENT ON COLUMN DEV_GIT_TAG.REPO IS '仓库地址';
COMMENT ON COLUMN DEV_GIT_TAG."RESOURCE" IS '资源文件';
COMMENT ON COLUMN DEV_GIT_TAG.COMMIT_ID IS '提交ID';
COMMENT ON COLUMN DEV_GIT_TAG.PUBLIC_COMMIT_IDS IS '公共依赖库';
COMMENT ON COLUMN DEV_GIT_TAG.NOTE IS '版本说明';
COMMENT ON COLUMN DEV_GIT_TAG.WHEN_CREATED IS '创建时间';
COMMENT ON COLUMN DEV_GIT_TAG.WHO_CREATED IS '创建人';

CREATE TABLE  SYS_CONFIG_GROUP (
    ID varchar(36) NOT NULL,
    APP_ID varchar(36),
    GROUP_NAME varchar(255) NOT NULL,
    GROUP_PATH varchar(255),
    WHEN_CREATED varchar(30),
    WHEN_MODIFIED varchar(30),
    WHO_CREATED varchar(36),
    WHO_MODIFIED varchar(36),
    NOTE varchar(255),
    PARENT_ID varchar(32),
    GROUP_TYPE int DEFAULT 1,
    LEAF_CONFIG clob,
    SORT int,
    ICON varchar(50),
    PRIMARY KEY (ID)
);
COMMENT ON COLUMN SYS_CONFIG_GROUP.ID IS '主键ID';
COMMENT ON COLUMN SYS_CONFIG_GROUP.APP_ID IS '关联应用';
COMMENT ON COLUMN SYS_CONFIG_GROUP.GROUP_NAME IS '组名称';
COMMENT ON COLUMN SYS_CONFIG_GROUP.GROUP_PATH IS '路径';
COMMENT ON COLUMN SYS_CONFIG_GROUP.WHEN_CREATED IS '创建时间';
COMMENT ON COLUMN SYS_CONFIG_GROUP.WHEN_MODIFIED IS '修改时间';
COMMENT ON COLUMN SYS_CONFIG_GROUP.WHO_CREATED IS '创建人员';
COMMENT ON COLUMN SYS_CONFIG_GROUP.WHO_MODIFIED IS '修改人员';
COMMENT ON COLUMN SYS_CONFIG_GROUP.NOTE IS '备注';
COMMENT ON COLUMN SYS_CONFIG_GROUP.PARENT_ID IS '父分组ID';
COMMENT ON COLUMN SYS_CONFIG_GROUP.GROUP_TYPE IS '分组层级';
COMMENT ON COLUMN SYS_CONFIG_GROUP.LEAF_CONFIG IS '配置格式json';
COMMENT ON COLUMN SYS_CONFIG_GROUP.SORT IS '排序';
COMMENT ON COLUMN SYS_CONFIG_GROUP.ICON IS '图标';


CREATE TABLE  DEV_MODEL_LATEST (
    ID varchar(36) NOT NULL,
    MODEL_NAME varchar(50),
    SOURCE_NAME varchar(50),
    VERSION_NAME varchar(100),
    VERSION_WHO varchar(100),
    VERSION_TIME varchar(20),
    DESCRIPTION varchar(255),
    DIAGRAM clob,
    INNER_VERSION number DEFAULT 0,
    CUSTOM_TYPE_MAPPING clob,
    APP_ID varchar(36),
    WHO_CREATED varchar(36),
    WHEN_CREATED varchar(20),
    WHO_MODIFIED varchar(36),
    WHEN_MODIFIED varchar(20),
    PRIMARY KEY (ID)
);
COMMENT ON COLUMN DEV_MODEL_LATEST.ID IS '主键ID';
COMMENT ON COLUMN DEV_MODEL_LATEST.MODEL_NAME IS '模型名称';
COMMENT ON COLUMN DEV_MODEL_LATEST.SOURCE_NAME IS '数据源名称';
COMMENT ON COLUMN DEV_MODEL_LATEST.VERSION_NAME IS '修订版本';
COMMENT ON COLUMN DEV_MODEL_LATEST.VERSION_WHO IS '修订人';
COMMENT ON COLUMN DEV_MODEL_LATEST.VERSION_TIME IS '修订时间';
COMMENT ON COLUMN DEV_MODEL_LATEST.DESCRIPTION IS '备注';
COMMENT ON COLUMN DEV_MODEL_LATEST.DIAGRAM IS '模型数据';
COMMENT ON COLUMN DEV_MODEL_LATEST.INNER_VERSION IS '内部版本号，用于服务端保存时校验';
COMMENT ON COLUMN DEV_MODEL_LATEST.CUSTOM_TYPE_MAPPING IS '用户自定义类型映射，当用户导入表出现系统未适配的字段类型时，提醒用户选择要转成什么类型';
COMMENT ON COLUMN DEV_MODEL_LATEST.APP_ID IS '所属应用ID';
COMMENT ON COLUMN DEV_MODEL_LATEST.WHO_CREATED IS '创建人';
COMMENT ON COLUMN DEV_MODEL_LATEST.WHEN_CREATED IS '创建时间';
COMMENT ON COLUMN DEV_MODEL_LATEST.WHO_MODIFIED IS '更新人';
COMMENT ON COLUMN DEV_MODEL_LATEST.WHEN_MODIFIED IS '更新时间';


CREATE TABLE  DEV_PAGE_TEMPLATE_ACTION_LOG (
    ID varchar(36) NOT NULL,
    ACTION_TYPE int NOT NULL,
    IS_COPY_ALL int,
    TEMPLATE_ID varchar(36) NOT NULL,
    APP_ID varchar(36),
    TEAM_ID varchar(36),
    ACTION_CONTENT clob,
    WHO_CREATED varchar(36) NOT NULL,
    WHEN_CREATED varchar(20) NOT NULL,
    PRIMARY KEY (ID)
);
COMMENT ON COLUMN DEV_PAGE_TEMPLATE_ACTION_LOG.ID IS '主键';
COMMENT ON COLUMN DEV_PAGE_TEMPLATE_ACTION_LOG.ACTION_TYPE IS '动作类型；1：模板复制；2：模板预览';
COMMENT ON COLUMN DEV_PAGE_TEMPLATE_ACTION_LOG.IS_COPY_ALL IS '是否全文复制';
COMMENT ON COLUMN DEV_PAGE_TEMPLATE_ACTION_LOG.TEMPLATE_ID IS '数据id，根据action_type指向不同的表';
COMMENT ON COLUMN DEV_PAGE_TEMPLATE_ACTION_LOG.APP_ID IS '关联应用';
COMMENT ON COLUMN DEV_PAGE_TEMPLATE_ACTION_LOG.TEAM_ID IS '关联团队';
COMMENT ON COLUMN DEV_PAGE_TEMPLATE_ACTION_LOG.ACTION_CONTENT IS '动作关联的内容，例如action_type为模板复制时，content就是复制的内容';
COMMENT ON COLUMN DEV_PAGE_TEMPLATE_ACTION_LOG.WHO_CREATED IS '创建人员';
COMMENT ON COLUMN DEV_PAGE_TEMPLATE_ACTION_LOG.WHEN_CREATED IS '创建时间';


CREATE TABLE  DEV_FILE_VERSION (
    ID varchar(36) NOT NULL,
    FILE_NAME varchar(255),
    PATH varchar(1000),
    OS_TYPE varchar(20),
    VERSION varchar(100),
    PATH_BY_PACKAGE varchar(1000),
    FILE_SIZE int,
    DESCRIPTION varchar(255),
    PARENT_PATH varchar(1000),
    WHEN_MODIFIED varchar(30),
    WHO_MODIFIED varchar(36),
    PRIMARY KEY (ID)
);
COMMENT ON COLUMN DEV_FILE_VERSION.ID IS 'ID';
COMMENT ON COLUMN DEV_FILE_VERSION.FILE_NAME IS '文件名';
COMMENT ON COLUMN DEV_FILE_VERSION.PATH IS '导致安装包的位置';
COMMENT ON COLUMN DEV_FILE_VERSION.OS_TYPE IS '操作系统类型';
COMMENT ON COLUMN DEV_FILE_VERSION.VERSION IS '版本号（vX.X.X结构）';
COMMENT ON COLUMN DEV_FILE_VERSION.PATH_BY_PACKAGE IS '所在package中的真实位置';
COMMENT ON COLUMN DEV_FILE_VERSION.FILE_SIZE IS '文件大小';
COMMENT ON COLUMN DEV_FILE_VERSION.DESCRIPTION IS '描述';
COMMENT ON COLUMN DEV_FILE_VERSION.PARENT_PATH IS '父目录';
COMMENT ON COLUMN DEV_FILE_VERSION.WHEN_MODIFIED IS '更新时间';
COMMENT ON COLUMN DEV_FILE_VERSION.WHO_MODIFIED IS '更新人';










































