CREATE TABLE  "SYS_DATA_CHANGE" ("ID" VARCHAR(32) NOT NULL, "NAME" VARCHAR(255), "TABLE_NAME" VARCHAR(255), "OBJECT_NAME" VARCHAR(255), "OPERATOR" VARCHAR(255), "OPER_TYPE" VARCHAR(255), "OPER_TIME" VARCHAR(255), "CONTENT" VARCHAR(255), PRIMARY KEY ("ID"));

CREATE TABLE  "NUMBER_REGULATION" ("ID" VARCHAR(36) NOT NULL, "SORT" VARCHAR(255), "TYPE" VARCHAR(255), "VALUE" VARCHAR(255), PRIMARY KEY ("ID"));

CREATE TABLE  "NUMBER_SERIAL" ("ID" VARCHAR(36) NOT NULL, "CREATE_TIME" VARCHAR(255), "NAME" VARCHAR(255), "NUMBER" VARCHAR(255), "REGULATIONID" VARCHAR(64), "REMARK" VARCHAR(255), "START_VALUE" VARCHAR(255), "STEP_VALUE" VARCHAR(255), "UPDATE_TIME" VARCHAR(255), PRIMARY KEY ("ID"));

CREATE TABLE  "SYS_AUTO_SERIAL" ("ID" VARCHAR(36) NOT NULL, "AUTO_NUM" INT, "CATEGORY" VARCHAR(100), "CREATE_TIME" VARCHAR(20), "CREATE_USER" VARCHAR(50), "KEY" VARCHAR(50), "LOCKED" INT DEFAULT 0, "NUM_LENGTH" INT, "START_NUM" INT, "STEP" INT, "TPL" VARCHAR(100), "TYPE" INT, "UPDATE_TIME" VARCHAR(20), "UPDATE_USER" VARCHAR(50), PRIMARY KEY ("ID"));

CREATE TABLE  "SYS_HINT_SELECT" ("ID" VARCHAR(36) NOT NULL, "CODE" VARCHAR(100), "DB_ID" VARCHAR(100), "FLOW_ID" VARCHAR(50), "REMARK" CLOB, "SELECT_FIELDS" CLOB, "SELECT_SQL" CLOB, "TYPE" VARCHAR(50), PRIMARY KEY ("ID"));

CREATE TABLE  "SYS_MQ_CHANNEL" ("ID" VARCHAR(36) NOT NULL, "BATCH_CONSUMER" INT, "CHANNEL_NAME" VARCHAR(50), "CONSUMER_GROUP" VARCHAR(50), "CONSUMER_THREAD" INT, "ENABLE" INT, "MESSAGE_NAME" VARCHAR(50), "TOPIC" VARCHAR(50), "ZK_ADDRESS" VARCHAR(50), PRIMARY KEY ("ID"));
