ALTER TABLE OPEN_ACCOUNT ADD APP_ID varchar(36);

ALTER TABLE SYS_NOTICE ADD IS_FORCE int;
COMMENT ON COLUMN SYS_NOTICE.IS_FORCE IS '是否重要 0: 否 1：是';

ALTER TABLE SYS_NOTICE ADD CONFIG clob;
COMMENT ON COLUMN SYS_NOTICE.CONFIG IS '团队头像';

ALTER TABLE DEV_APPLICATION ADD DEPEND_DATASOURCES varchar2(2048 char);
COMMENT ON COLUMN DEV_APPLICATION.DEPEND_DATASOURCES IS '依赖数据源';

ALTER TABLE DEV_APPLICATION ADD DEPEND_APPS varchar2(2048 char);
COMMENT ON COLUMN DEV_APPLICATION.DEPEND_APPS IS '依赖应用';

ALTER TABLE DEV_APPLICATION ADD APP_NAMESPACE varchar(255);
COMMENT ON COLUMN DEV_APPLICATION.APP_NAMESPACE IS '应用命名空间';

ALTER TABLE KFAAS_LIB ADD ID varchar(36) NOT NULL;
ALTER TABLE KFAAS_LIB ADD CREATE_TIME varchar(20);
ALTER TABLE KFAAS_LIB ADD CREATE_USER varchar(255);
ALTER TABLE KFAAS_LIB ADD JAR_NAME varchar(255);
ALTER TABLE KFAAS_LIB ADD UPDATE_TIME varchar(20);
ALTER TABLE KFAAS_LIB ADD UPDATE_USER varchar(255);
ALTER TABLE KFAAS_LIB DROP COLUMN jarname;
ALTER TABLE KFAAS_LIB DROP COLUMN createtime;
ALTER TABLE KFAAS_LIB DROP COLUMN updatetime;
ALTER TABLE KFAAS_LIB DROP COLUMN createuser;
ALTER TABLE KFAAS_LIB DROP COLUMN updateuser;
ALTER TABLE KFAAS_LIB MODIFY STATUS int;

ALTER TABLE REP_DATASET ADD DATASET_SEARCH_ID varchar(32);
COMMENT ON COLUMN REP_DATASET.DATASET_SEARCH_ID IS '是否为搜索数据';

ALTER TABLE REP_DATASET ADD SHAPE int;
COMMENT ON COLUMN REP_DATASET.SHAPE IS '是否为自定义SQL';

ALTER TABLE REP_DATASET ADD TEMPLATE int;
COMMENT ON COLUMN REP_DATASET.TEMPLATE IS '是否为Excel模板（0：否，1：是）';

ALTER TABLE REP_DATASET ADD REP_CRON varchar(50);
COMMENT ON COLUMN REP_DATASET.REP_CRON IS '模板报表定时任务Cron表达式';

-- ALTER TABLE SYS_AUTH_SOURCE ADD WHOCREATED varchar(36);

ALTER TABLE DEV_PAGE_TEMPLATE ADD VIEW_NUM int DEFAULT 0;
COMMENT ON COLUMN DEV_PAGE_TEMPLATE.VIEW_NUM IS '预览量';

ALTER TABLE DEV_PAGE_TEMPLATE ADD COPY_NUM int DEFAULT 0;
COMMENT ON COLUMN DEV_PAGE_TEMPLATE.COPY_NUM IS '被复制的次数；copy_num = copy_all_num+copy_part_num';

ALTER TABLE DEV_PAGE_TEMPLATE ADD COPY_ALL_NUM int DEFAULT 0;
COMMENT ON COLUMN DEV_PAGE_TEMPLATE.COPY_ALL_NUM IS '被全量复制的次数';

ALTER TABLE DEV_PAGE_TEMPLATE ADD COPY_PART_NUM int DEFAULT 0;
COMMENT ON COLUMN DEV_PAGE_TEMPLATE.COPY_PART_NUM IS '被部分复制的次数';

ALTER TABLE OPEN_API_LOG ADD API_ID varchar(36);
COMMENT ON COLUMN OPEN_API_LOG.API_ID IS '接口id';

ALTER TABLE SYS_LOGIC_FLOW ADD I18N_KEYS clob;
COMMENT ON COLUMN SYS_LOGIC_FLOW.I18N_KEYS IS '国际化键名';

ALTER TABLE SYS_UNIT ADD UNIT_CODE varchar(100);
COMMENT ON COLUMN SYS_UNIT.UNIT_CODE IS '机构编码';

ALTER TABLE SYS_CONFIG ADD GROUP_ID varchar(36);
COMMENT ON COLUMN SYS_CONFIG.GROUP_ID IS '关联组';

ALTER TABLE SYS_INSTANCE ADD CLUSTER_NO int;
COMMENT ON COLUMN SYS_INSTANCE.CLUSTER_NO IS '集群号';

ALTER TABLE DEV_SQL_SCRIPT ADD ID varchar(36) NOT NULL;

















