# region server
server.servlet.context-path=/api
server.port=8080
# endregion server

# region spring
spring.jackson.date-format = yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.serialization.write-dates-as-timestamps=true
spring.servlet.multipart.enabled=true
# endregion spring

# region database
database.sources.db.databaseType=kdb
database.sources.db.channel=kdbHttp
database.sources.db.innerType=MySql
database.sources.db.server=http://192.168.2.103:8001
database.sources.db.executeSqlApi=/api/execute
# DB??:?????:?????
database.sources.db.dbName=db:MySql:MySql,kingDB:KingDB:HSQLDB
# endregion database

# region encrypt
encrypt.mode=base64
# endregion encrypt

# region auth
app.auth.enable=false
app.auth.iss=kingsware
app.auth.tokenExpireMinutes=120
app.auth.tokenSecret=3kj0ByucpznafmRd
# endregion auth

# region file
file.base-path = /Users/andyzheng/tmp/upload


# endregion file
