# region ?????
# KDB??????????????????????kdb???????????????????
database.kdb-join-in-one = false
# KDB????????kdb-join-in-one?true????????
database.kdb-master = default
# ?????
database.db.database-type=kdb
database.db.server=http://127.0.0.1
database.db.dbName=db
# endregion ?????
