# region server
server.servlet.context-path=/
server.port=8080
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/plain,text/css,application/x-javascript
# endregion server

# region spring
spring.jackson.date-format = yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.serialization.write-dates-as-timestamps=true
spring.servlet.multipart.enabled=true
# endregion spring

# region database
database.sources.db.databaseTypekdbHttp=kdb
database.sources.db.channel=kdbHttp
database.sources.db.innerType=Postgresql
database.faas-port=10081
database.faas-ip=10.11.1.77
database.sources.db.server=http://10.11.1.181:10081
database.sources.db.executeSqlApi=/api/execute
# DB??:?????:?????
database.sources.db.dbName=db:MySql:Postgresql,kingDB:kingDB:HSQLDB
# endregion database

# region encrypt
encrypt.mode=base64
# endregion encrypt

# region auth
app.ignore.urls=**/websocket;**/eiac
app.auth.enable=true
app.auth.iss=kingsware
app.auth.tokenExpireMinutes=120
app.auth.tokenSecret=3kj0ByucpznafmRd
app.auth.login-session-one=false
app.auth.mock-session-expire-minutes=300
# endregion auth

# region pine dev mode
app.mode.dev=true
# endregion pine dev mode

# region file
file.base-path=upload
app.file-local-to-faas=true
# endregion file

# region k-flow
app.k-flow.enable=true
# endregion k-flow

app.ui=/Users/mac/IdeaProjects/k-cli-ui/ui/
app.ui.prefix=${server.servlet.context-path}
