# region server
server.servlet.context-path=/
server.port=8080
# endregion server

# region spring
spring.jackson.date-format = yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.serialization.write-dates-as-timestamps=true
spring.servlet.multipart.enabled=true
# endregion spring

# region database
database.sources.db.databaseType=kdb
database.sources.db.channel=kdbHttp
database.sources.db.innerType=MySql
#database.sources.db.server=http://192.168.2.111:8030
database.sources.db.server=http://10.11.2.215:8030
#database.sources.db.server=http://localhost:10081
database.sources.db.executeSqlApi=/api/execute4debug
# DB??:?????:?????
database.sources.db.dbName=db:MySql:MySql,kingDB:kingDB:HSQLDB,oracle:OracleTest:Oracle
# endregion database

# region encrypt
encrypt.mode=base64
# endregion encrypt

# region auth
app.auth.enable=true
app.auth.iss=kingsware
app.auth.tokenExpireMinutes=120
app.auth.tokenSecret=3kj0ByucpznafmRd
app.auth.login-session-one=false
app.auth.mock-session-expire-minutes=300
# endregion auth

# region pine dev mode
app.mode.dev=true
# endregion pine dev mode

# region file
file.base-path=upload
app.file-local-to-faas=true

# region k-flow
app.k-flow.enable=true
# endregion k-flow

# WaterPath
#file.WaterPath = ////192.168.106.113//
file.WaterPath = /Users/andyzheng/tmp/water
# schedule.QueueTask.cron
schedule.QueueTask.cron=0 0/1 * * * ?
# schedule.WaterCheckBalanceTask.cron
schedule.WaterCheckBalanceTask.cron=0 0 0/2 * * ?
# endregion file
