# region server
server.servlet.context-path=/
server.port=8080
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,text/javascript,text/css,application/javascript
server.compression.min-response-size=256
# endregion server

# region pine server
pine.server.host=127.0.0.1
#  endregion pine server

# region spring
spring.jackson.date-format = yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.serialization.write-dates-as-timestamps=true
spring.servlet.multipart.enabled=true
# endregion spring

# region database
database.sources.db.databaseType=kdb
database.sources.db.channel=kdbHttp
database.sources.db.innerType=MySql
database.sources.db.server=http://10.11.2.46:10081
database.sources.db.executeSqlApi=/api/execute
# DB??:?????:?????
database.sources.db.dbName=db:MySql:MySql,kingDB:kingDB:HSQLDB
# endregion database

# region encrypt
encrypt.mode=base64
encrypt.aes.secret=PsLZlcuUJBUB8yPo
# endregion encrypt

# region pine dev mode
app.mode.dev=true
# endregion pine dev mode

# region k-flow
app.file-local-to-faas=true
app.k-flow.enable=true
# endregion k-flow

# region auth
app.auth.enable=false
app.auth.iss=kingsware
app.auth.tokenExpireMinutes=120
app.auth.tokenSecret=3kj0ByucpznafmRd
app.auth.login-session-one=false
app.auth.mock-session-expire-minutes=-1
# endregion auth

file.base-path = upload

file.write-list = png,jpg,jpeg,gif,svg,html,tif,bmp,pic,pdf,doc,docx,xls,xlsx,ppt,pptx,csv,jar,license,wps,txt,rar,zip,gz,wav,mp3,wma,aac,flac,avi,mpg,mov,mp4,pine,json,xml

file.WaterPath = upload
schedule.QueueTask.cron=0 0/1 * * * ?

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

schedule.WaterCheckBalanceTask.cron=0 0 5 * * ?
