# region server
server.servlet.context-path=/
server.port=8080
server.compression.enabled=true
server.tomcat.accept-count=1000
server.tomcat.max-connections=10000
server.tomcat.threads.min-spare=100
server.tomcat.threads.max=800
# endregion server

# region spring
spring.jackson.date-format = yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.serialization.write-dates-as-timestamps=true
spring.servlet.multipart.enabled=true
# endregion spring

# region database
database.sources.db.databaseType=kdb
database.sources.db.channel=kdbHttp
database.sources.db.innerType=MySql
database.sources.db.server=http://10.11.2.46:10081
database.sources.db.executeSqlApi=/api/execute4debug
# DB??:?????:?????
database.sources.db.dbName=db:MySql:MySql,kingDB:kingDB:HSQLDB
database.app2faas[0].id=db496ec8b5114b6a91a9710a31f845fd
database.app2faas[0].server=http://10.11.2.69:8030
# endregion database

# region encrypt
encrypt.mode=base64
# endregion encrypt

# region auth
app.auth.enable=true
app.auth.iss=kingsware
app.auth.tokenExpireMinutes=120
app.auth.tokenSecret=3kj0ByucpznafmRd
app.auth.login-session-one=false
app.auth.mock-session-expire-minutes=0
app.auth.open-validate-code=false
app.auth.password-check-version=v2

# endregion auth

# region pine dev mode
app.mode.dev=true
app.file-local-to-faas=true
app.ui.enableSSR=false
# endregion pine dev mode

# region file
file.base-path =  /usr/local/kfaas/server/upload

# region k-flow
app.k-flow.enable=true
# endregion k-flow
network.ip=192.168.107.218

# app.kfaas.tcp.servers=127.0.0.1:10241
app.ui=/Users/ronle/code/k-cli-ui/dev-ui/
app.ui.prefix=${server.servlet.context-path}
app.sub-title=63Xb+NGDIb5eqPSlnIpNOXKQJ3B9YiJbsDAY446leBxo5WXYEoND7p9aVHrezPxz2NirEBAdGejcaYpzl1HHpw==

# log config
# log config
# app.operate.log-filter=*sys-users/query;



