# region server
server.servlet.context-path=/
server.port=8080
# endregion server

# region spring
spring.jackson.date-format = yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.serialization.write-dates-as-timestamps=true
spring.servlet.multipart.enabled=true
# endregion spring

# region database
database.sources.db.databaseType=kdb
database.sources.db.channel=kdbHttp
database.sources.db.innerType=MySql
database.sources.db.server=http://localhost:8001
database.sources.db.executeSqlApi=/api/execute
# DB??:?????:?????
database.sources.db.dbName=db:MySql:MySql,kingDB:kingDB:HSQLDB,oracle:Oracle2:Oracle
# endregion database

# region encrypt
encrypt.mode=base64
# endregion encrypt

# region auth
app.auth.enable=true
app.auth.iss=kingsware
app.auth.tokenExpireMinutes=120
app.auth.tokenSecret=3kj0ByucpznafmRd
# endregion auth

# region file
file.base-path = C:/kingsware/kafm/upload

# WaterPath
#file.WaterPath = ////192.168.106.113//
file.WaterPath = C://
# schedule.QueueTask.cron
schedule.QueueTask.cron=0 0/1 * * * ?
# schedule.WaterCheckBalanceTask.cron
schedule.WaterCheckBalanceTask.cron=0 0 5 * * ?
# endregion file


