-- ----------------------------
-- Table structure for sys_unit
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_unit` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `name` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '名称',  `parent_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '上级单位ID',  `path` text COLLATE utf8mb4_bin NOT NULL COMMENT '层次关系，自动生成',  `leader` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '负责人',  `mobile` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '联系电话',  `email` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '电子邮箱',  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '部门状态， 0：停用 1：正常',  `note` text COLLATE utf8mb4_bin COMMENT '备注',  `order_num` int(10) DEFAULT '0' COMMENT '排序 ',  `who_created` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '修改人员',  `when_modified` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '修改时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-单位机构';
-- ----------------------------
-- Table structure for sys_user
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_user` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `username` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '用户名',  `password` varchar(256) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '密码',  `real_name` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '用户姓名',  `mobile` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '手机号码',  `email` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '电子邮箱',  `sex` tinyint(4) DEFAULT NULL COMMENT '性别 0:男 1:女',  `sys_unit_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '归属部门',  `post` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '岗位',  `status` tinyint(4) DEFAULT '1' COMMENT '状态 1：正常 0：禁用',  `note` text COLLATE utf8mb4_bin COMMENT '备注',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改时间',  `deleted` tinyint(4) DEFAULT '0' COMMENT '逻辑删除 0:正常 1：删除',  `avatar` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE,  UNIQUE KEY `idx_username_uindex` (`username`) USING BTREE,  KEY `fk_sys_unit_id` (`sys_unit_id`) USING BTREE,  CONSTRAINT `fk_sys_unit_id` FOREIGN KEY (`sys_unit_id`) REFERENCES `sys_unit` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-用户';
-- ----------------------------
-- Table structure for sys_role
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_role` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `name` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '名称',  `code` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '编码',  `note` text COLLATE utf8mb4_bin COMMENT '备注',  `status` tinyint(4) DEFAULT NULL COMMENT '是否有效 0:否 1：是',  `who_created` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '修改人员',  `when_modified` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '修改时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE,  UNIQUE KEY `idx_name_uindex` (`name`) USING BTREE,  UNIQUE KEY `idx_coce_uindex` (`code`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-角色';
-- ----------------------------
-- Table structure for sys_user_role
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_user_role` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `sys_user_id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '名称',  `sys_role_id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '编码',  `who_created` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '创建时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE,  UNIQUE KEY `idx_sys_user_role_uindex` (`sys_user_id`,`sys_role_id`) USING BTREE,  KEY `fk_sys_role_key` (`sys_role_id`) USING BTREE,  KEY `fk_sys_user_role_user` (`sys_user_id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-用户角色表';
-- ----------------------------
-- Table structure for dev_api
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_api` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '主键',  `api_name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '接口名称',  `application_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '归属应用ID',  `api_url` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '接口路径',  `api_note` text COLLATE utf8mb4_bin COMMENT '接口描述',  `api_tags` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '标签',  `api_method` varchar(32) COLLATE utf8mb4_bin DEFAULT 'get' COMMENT '请求方式',  `api_argv_type` int(4) DEFAULT NULL COMMENT '参数组装方式',  `api_req_argv` text COLLATE utf8mb4_bin COMMENT '请求参数',  `api_rsp_argv` text COLLATE utf8mb4_bin COMMENT '响应结果',  `api_result_handler` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '结果处理类',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人',  `when_modified` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改时间',  `api_flow_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程ID',  `api_code` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '接口编码',  `call_type` int(4) DEFAULT NULL COMMENT '调试方式',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for dev_application
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_application` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '应用ID',  `name` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应用名',  `short_name` varchar(30) COLLATE utf8mb4_bin NOT NULL COMMENT '应用短英文名（用于数据库等前缀命名），- 必须唯一，- 必须为纯英文、小写字母命名\n- 用于创建业务目录、数据库，',  `description` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应用介绍',  `enable_status` tinyint(1) DEFAULT NULL COMMENT '可用状态',  `dev_status` tinyint(1) DEFAULT NULL COMMENT '开发状态，0: 新建1: 确认版本2: 有更新',  `version` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '当前发布版本',  `who_in_charge` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '负责人',  `system_logo` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应用图标',  `app_type` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应用类型：可多个，逗号分隔，0: PC Web应用，1：移动端Web应用，2： 小程序，3： APP',  `default_path` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '默认路径',  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_created` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '修改时间',  `who_modified` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人',  `faas_port` int(11) DEFAULT NULL COMMENT 'faas端口号',  `pine_port` int(11) DEFAULT NULL COMMENT '青松端口号',  `data_source` varchar(1000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '数据源配置',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for dev_application_version_history
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_application_version_history` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_created` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应用ID',  `version` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '版本',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for dev_document
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_document` (  `id` varchar(255) COLLATE utf8mb4_bin NOT NULL COMMENT 'id',  `name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '标题',  `path` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '文件路径',  `content` mediumtext COLLATE utf8mb4_bin COMMENT '正文',  `parent_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '父节点id',  `order` int(4) NOT NULL AUTO_INCREMENT COMMENT '目录排序',  `when_created` date DEFAULT NULL COMMENT '创建时间',  `who_created` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '创建人',  `deleted` tinyint(4) DEFAULT '0' COMMENT '逻辑删除 0:正常 1：删除',  PRIMARY KEY (`order`)) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for dev_page
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_page` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '修改时间',  `who_created` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人',  `who_modified` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人',  `deleted` tinyint(4) DEFAULT '0' COMMENT '删除标识',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应用ID',  `name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '页面名称',  `description` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '页面介绍',  `path` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '访问路径 ',  `app_type` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应用类型：可多个，逗号分隔，0: PC Web应用，1：移动端Web应用，2： 小程序，3： APP',  `login_required` tinyint(1) DEFAULT NULL COMMENT '是否需要登录才可以访问',  `enable_status` tinyint(1) DEFAULT NULL COMMENT '可用状态',  `dev_status` tinyint(1) DEFAULT NULL COMMENT '开发状态',  `page_json` longtext COLLATE utf8mb4_bin COMMENT '页面数据化JSON',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for dev_page_history
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_page_history` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT 'ID',  `page_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '页面ID',  `page_json` longtext COLLATE utf8mb4_bin COMMENT '页面JSON',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_created` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for dev_sql_run
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_sql_run` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT 'id',  `version` int(11) NOT NULL COMMENT '关联版本号',  `md5` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'md5',  `when_created` timestamp NULL DEFAULT NULL COMMENT '执行时间',  `execution_time` int(11) DEFAULT NULL COMMENT '执行时长（毫秒）',  `success` tinyint(4) NOT NULL COMMENT '是否成功',  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for dev_sql_script
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_sql_script` (  `sql` longtext COLLATE utf8mb4_bin NOT NULL COMMENT '执行脚本',  `description` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '描述',  `version` int(11) NOT NULL AUTO_INCREMENT COMMENT '版本号',  `is_once` tinyint(4) NOT NULL DEFAULT '1' COMMENT '是否只执行1次',  PRIMARY KEY (`version`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for dev_team
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_team` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '团队ID',  `name` varchar(100) COLLATE utf8mb4_bin NOT NULL COMMENT '团队名称',  `owner` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '团队负责人',  `description` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '团队简介',  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_created` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '修改时间',  `who_modified` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人',  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='团队表';
-- ----------------------------
-- Table structure for dev_team_app
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_team_app` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '主键ID',  `team_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '团队ID',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '当类型为应用团队时，必须有应用APP_ID',  `team_type` tinyint(1) NOT NULL COMMENT '团队类型（1：平台团队，2：应用团队）',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_created` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人',  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for dev_team_member
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_team_member` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT 'id',  `team_id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '团队ID',  `user_id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '用户ID',  `when_join` timestamp NULL DEFAULT NULL COMMENT '加入时间',  `who_invite` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '邀请人',  `team_role_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '团队角色',  `is_owner` tinyint(1) DEFAULT NULL COMMENT '是否为团队负责人',  `app_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`),  UNIQUE KEY `uni_user_team_app` (`team_id`,`user_id`,`app_id`) USING BTREE COMMENT '唯一约束') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='团队成员表';
-- ----------------------------
-- Table structure for dev_topological
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_topological` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '修改时间',  `who_created` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人',  `who_modified` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人',  `deleted` tinyint(4) DEFAULT '0' COMMENT '删除标识',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应用ID',  `name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '页面名称',  `description` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '页面介绍',  `page_json` longtext COLLATE utf8mb4_bin COMMENT '页面数据化JSON',  `enable_status` tinyint(1) DEFAULT NULL COMMENT '可用状态') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='拓扑图管理';
-- ----------------------------
-- Table structure for dev_view_model
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_view_model` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '名称',  `note` text COLLATE utf8mb4_bin COMMENT '描述',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '修改时间',  `deleted` int(11) DEFAULT '0' COMMENT '逻辑删除',  `tag` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '标签，多个用逗号分隔',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-视图模型表';
-- ----------------------------
-- Table structure for dev_view_model_field
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_view_model_field` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `view_model_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '模型ID',  `field` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '键名',  `label` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '标签',  `type` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '数据类型',  `format_type` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '格式类型',  `format_pattern` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '格式规则',  `default_text` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '默认显示',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '修改时间',  `hidden` int(11) DEFAULT '0' COMMENT '是否隐藏',  `order_num` int(11) DEFAULT '0' COMMENT '排序',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-视图模型属性';
-- ----------------------------
-- Table structure for dev_view_model_flow
-- ----------------------------
CREATE TABLE IF NOT EXISTS`dev_view_model_flow` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL,  `flow_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流水ID',  `view_model_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '模型ID',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '修改时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-视图模型和流程关联';
-- ----------------------------
-- Table structure for sys_api
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_api` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '主键',  `api_name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '接口名称',  `api_url` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '接口路径',  `api_note` text COLLATE utf8mb4_bin COMMENT '接口描述',  `api_tags` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '标签',  `api_method` varchar(32) COLLATE utf8mb4_bin DEFAULT 'get' COMMENT '请求方式',  `api_argv_type` int(4) DEFAULT NULL COMMENT '参数组装方式',  `api_req_argv` text COLLATE utf8mb4_bin COMMENT '请求参数',  `api_rsp_argv` text COLLATE utf8mb4_bin COMMENT '响应结果',  `api_result_handler` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '结果处理类',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人',  `when_modified` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改时间',  `api_flow_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程ID',  `api_code` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '接口编码',  `call_type` int(4) DEFAULT NULL COMMENT '调试方式',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for sys_base
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_base` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '名称',  `code` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '编码',  `note` text COLLATE utf8mb4_bin COMMENT '备注',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改时间',  `is_test` tinyint(4) DEFAULT NULL,  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for sys_config
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_config` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT 'ID',  `name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '参数名称',  `code` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '参数键名',  `value` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '参数键值',  `is_sys` tinyint(4) DEFAULT NULL COMMENT '是否系统内置',  `note` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备注',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改时间',  `value_type` tinyint(4) DEFAULT '0',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for sys_data_access
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_data_access` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '名称',  `status` tinyint(4) DEFAULT NULL COMMENT '启用状态',  `note` text COLLATE utf8mb4_bin COMMENT '备注',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-数据访问组';
-- ----------------------------
-- Table structure for sys_data_resource
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_data_resource` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '名称',  `table_name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '表名',  `label_field` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '标签列',  `value_field` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '值列',  `query_sql` text COLLATE utf8mb4_bin COMMENT '查询SQL',  `is_tree` tinyint(4) DEFAULT NULL COMMENT '是否树形结构',  `is_only_leaf` tinyint(4) DEFAULT NULL COMMENT '是否只选树叶',  `status` tinyint(4) DEFAULT NULL COMMENT '启用状态',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改时间',  `extra_sql` text COLLATE utf8mb4_bin COMMENT '权限附加SQL',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-数据资源配置';
-- ----------------------------
-- Table structure for sys_data_access_resource
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_data_access_resource` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `data_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '名称',  `access_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '编码',  `table_name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备注',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE,  KEY `fk_sys_data_access_group_access` (`access_id`) USING BTREE,  CONSTRAINT `fk_sys_data_access_group_access` FOREIGN KEY (`access_id`) REFERENCES `sys_data_access` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-数据访问组和资源';
-- ----------------------------
-- Table structure for sys_data_access_user
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_data_access_user` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `sys_user_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '用户id',  `sys_data_access_id` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '数据访问组id',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE,  KEY `fk_sys_data_access_group_user` (`sys_user_id`) USING BTREE,  KEY `fk_sys_data_access_group_group_id` (`sys_data_access_id`) USING BTREE,  CONSTRAINT `fk_sys_data_access_group_group_id` FOREIGN KEY (`sys_data_access_id`) REFERENCES `sys_data_access` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,  CONSTRAINT `fk_sys_data_access_group_user` FOREIGN KEY (`sys_user_id`) REFERENCES `sys_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-用户和数据访问组';

-- ----------------------------
-- Table structure for sys_dict
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_dict` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '名称',  `code` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '编码',  `note` text COLLATE utf8mb4_bin COMMENT '备注',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE,  UNIQUE KEY `idx_name_uindex` (`name`) USING BTREE,  UNIQUE KEY `idx_code_uindex` (`code`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-字典';
-- ----------------------------
-- Table structure for sys_dict_item
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_dict_item` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '名称',  `group_name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '组名',  `sys_dict_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '字典id',  `code` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '编码',  `value` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '值',  `order_num` int(8) DEFAULT NULL COMMENT '排序',  `note` text COLLATE utf8mb4_bin COMMENT '备注',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE,  UNIQUE KEY `idx_sys_dict_id_name_uindex` (`name`,`sys_dict_id`) USING BTREE,  UNIQUE KEY `idx_sys_dict_id_value_uindex` (`sys_dict_id`,`value`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-字典项';
-- ----------------------------
-- Table structure for sys_file
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_file` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `file_name` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '文件名称',  `file_original_name` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '原始文件名',  `file_size` int(11) DEFAULT NULL COMMENT '文件大小(Byte)',  `file_ext` text COLLATE utf8mb4_bin COMMENT '文件扩展名',  `file_md5` varchar(40) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '文件MD5值',  `file_from` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '文件来源',  `save_type` int(4) DEFAULT NULL COMMENT '存储方式 0：数据库 1：本地磁盘',  `file_path` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '存储路径',  `file_content` longtext COLLATE utf8mb4_bin COMMENT '文件内容，只有存数据库时才有值',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-文件表';
-- ----------------------------
-- Table structure for sys_logic_flow
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_logic_flow` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT 'ID',  `name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '名称',  `flow_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流程ID',  `application_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应用ID',  `tags` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '标签',  `in_argv` text COLLATE utf8mb4_bin COMMENT '输入参数',  `out_argv` text COLLATE utf8mb4_bin COMMENT '输出参数',  `sub_flow_ids` text COLLATE utf8mb4_bin COMMENT '子流程ID列表',  `note` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备注',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '修改时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-逻辑流';
-- ----------------------------
-- Table structure for sys_login_log
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_login_log` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `operate_time` timestamp NULL DEFAULT NULL COMMENT '访问时间',  `operator` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '访问人员',  `ip` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '来访IP',  `times` int(10) DEFAULT NULL COMMENT '耗时(ms)',  `response_code` int(11) DEFAULT NULL COMMENT '响应码',  `response_message` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '响应消息',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-用户登录日志';
-- ----------------------------
-- Table structure for sys_menu
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_menu` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `name` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '名称',  `parent_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '上级菜单ID',  `icon` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '图标',  `code` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '编码',  `router_path` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '路由路径',  `component_path` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '组件路径',  `is_hidden` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否隐藏',  `menu_type` char(1) COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '菜单类型（M目录 C菜单 F按钮）',  `api_codes` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '接口编码，多个用逗号分隔',  `open_mode` tinyint(4) NOT NULL COMMENT '打开方式 0:页签 1:新窗口',  `keep_alive` tinyint(4) DEFAULT NULL COMMENT '是否刷新 0: 否 1：是',  `path` text COLLATE utf8mb4_bin NOT NULL COMMENT '菜单层级关系，自动生成',  `order_num` int(4) NOT NULL DEFAULT '0' COMMENT '排序',  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '可用状态',  `who_created` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '修改人员',  `when_modified` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '修改时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '所属应用ID',  `data_type` tinyint(2) DEFAULT NULL COMMENT '数据类型：0系统，1业务应用, 2开发平台',  `theme` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'layout主题',  `page_type` tinyint(2) DEFAULT NULL COMMENT '页面渲染方式：0 Vue， 1 JSON',  `sidebar_nav_mode` tinyint(2) DEFAULT NULL COMMENT '侧边菜单显示模式：0 不显示，1 从一级菜单开始显示，2 从二级菜单开始显示, 3 显示二级以下菜单',  `top_nav_mode` tinyint(2) DEFAULT NULL COMMENT '顶部菜单显示模式：0 完全不显示, 1 不显示nav，2 从一级菜单开始显示，3 从二级菜单开始显示',  `main_mode` tinyint(2) DEFAULT NULL COMMENT '内容区显示样式：0 自动撑开，1 居中',  `page_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联页面',  `full_path` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '完整路径（根据层级结构、router_path拼接的完整路径）',  `is_dev` tinyint(1) DEFAULT '0' COMMENT '菜单是否为开发者模式菜单',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-菜单';
-- ----------------------------
-- Table structure for sys_notice
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_notice` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '消息ID',  `title` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '通知标题',  `content` text COLLATE utf8mb4_bin COMMENT '通知内容',  `type` tinyint(2) DEFAULT NULL COMMENT '通知类型，1：系统维护通知，2：公告',  `status` tinyint(2) NOT NULL DEFAULT '1' COMMENT '启用状态：0：待启用，1：已启用',  `who_created` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '更新人',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '更新时间',  `deleted` tinyint(1) DEFAULT NULL COMMENT '逻辑删除，0：未删除，1：已删除',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for sys_notice_record
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_notice_record` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '通知记录ID',  `from_who` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '发送人',  `to_who` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '接收人',  `notice_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联通知',  `is_read` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否已读，0：未读，1：已读',  `read_time` timestamp NULL DEFAULT NULL COMMENT '阅读通知时间',  `notice_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '接收通知时间',  `title` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '通知标题',  `content` text COLLATE utf8mb4_bin COMMENT '通知内容',  `to_who_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '接收人名称',  `from_who_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '发送人名称',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- ----------------------------
-- Table structure for sys_online_user
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_online_user` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `user_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '用户id',  `login_time` timestamp NULL DEFAULT NULL COMMENT '登录时间',  `login_ip` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '登录ip',  `login_token` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '令牌',  `expire_time` timestamp NULL DEFAULT NULL COMMENT '失效时间',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-在线用户';
-- ----------------------------
-- Table structure for sys_operate_log
-- ----------------------------
CREATE TABLE IF NOT EXISTS `sys_operate_log` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `module` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '模块',  `action` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '动作',  `url` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '路径',  `operate_time` timestamp NULL DEFAULT NULL COMMENT '访问时间',  `operator` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '访问人员',  `ip` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '来访IP',  `times` int(10) DEFAULT NULL COMMENT '耗时(ms)',  `request_body` text COLLATE utf8mb4_bin COMMENT '请求内容体',  `response_code` int(11) DEFAULT NULL COMMENT '响应码',  `response_message` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '响应消息',  `when_created` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE,  KEY `idx_sys_operate_time` (`operate_time`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-操作日志';
-- ----------------------------
-- Table structure for sys_role_menu
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_role_menu` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `sys_menu_id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '名称',  `sys_role_id` varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '编码',  `who_created` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '创建人员',  `when_created` varchar(20) COLLATE utf8mb4_bin NOT NULL COMMENT '创建时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE,  UNIQUE KEY `idx_sys_role_menu_uindex` (`sys_menu_id`,`sys_role_id`) USING BTREE,  KEY `fk_sys_role` (`sys_role_id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-单位机构';
-- ----------------------------
-- Table structure for sys_task
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_task` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `name` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '任务名称',  `cron` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '定时表达式',  `distributed` tinyint(4) DEFAULT NULL COMMENT '是否分布式',  `application_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应用ID',  `task_type` tinyint(4) DEFAULT '1' COMMENT '任务类型',  `task_resource_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '任务资源ID',  `class_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '类名',  `enable` tinyint(4) DEFAULT '1' COMMENT '启用状态',  `last_execute_status` tinyint(4) DEFAULT NULL COMMENT '最后执行状态 1：成功 0：失败',  `last_execute_msg` text COLLATE utf8mb4_bin COMMENT '最后执行错误信息',  `last_execute_time` timestamp NULL DEFAULT NULL COMMENT '上次执行时间',  `last_execute_take` int(11) DEFAULT NULL COMMENT '上次执行消耗',  `lock_status` tinyint(4) DEFAULT '0' COMMENT '锁定状态',  `lock_for_most` int(8) DEFAULT '30' COMMENT '最多锁定时长(秒)',  `lock_for_least` int(8) DEFAULT '1' COMMENT '最少锁定时长(秒)',  `lock_for_time` timestamp NULL DEFAULT NULL COMMENT '锁定时间',  `note` text COLLATE utf8mb4_bin COMMENT '备注',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '修改时间',  `app_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '关联应用',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-任务表';
-- ----------------------------
-- Table structure for sys_view_model
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_view_model` (  `id` varchar(36) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '名称',  `note` text COLLATE utf8mb4_bin COMMENT '描述',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '修改时间',  `deleted` int(11) DEFAULT '0' COMMENT '逻辑删除',  `tag` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '标签，多个用逗号分隔',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-视图模型表';
-- ----------------------------
-- Table structure for sys_view_model_field
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_view_model_field` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL COMMENT '主键',  `view_model_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '模型ID',  `field` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '键名',  `label` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '标签',  `type` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '数据类型',  `format_type` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '格式类型',  `format_pattern` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '格式规则',  `default_text` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '默认显示',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '修改时间',  `hidden` int(11) DEFAULT '0' COMMENT '是否隐藏',  `order_num` int(11) DEFAULT '0' COMMENT '排序') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-视图模型属性';
-- ----------------------------
-- Table structure for sys_view_model_flow
-- ----------------------------
CREATE TABLE IF NOT EXISTS`sys_view_model_flow` (  `id` varchar(32) COLLATE utf8mb4_bin NOT NULL,  `flow_id` varchar(36) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '流水ID',  `view_model_id` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '模型ID',  `who_created` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人员',  `when_created` timestamp NULL DEFAULT NULL COMMENT '创建时间',  `who_modified` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人员',  `when_modified` timestamp NULL DEFAULT NULL COMMENT '修改时间',  PRIMARY KEY (`id`) USING BTREE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='系统表-视图模型和流程关联';
INSERT INTO `sys_user` (`id`, `username`, `password`, `real_name`, `mobile`, `email`, `sex`, `sys_unit_id`, `post`, `status`, `note`, `who_created`, `when_created`, `who_modified`, `when_modified`, `deleted`, `avatar`, `app_id`) VALUES ('056fb0eeb9a44cb0953534b4c0ca01fa', 'admin', 'MTIzNDU2', '超级管理员', NULL, NULL, 1, NULL, NULL, 1, NULL, '', '2021-12-29 16:36:46', '056fb0eeb9a44cb0953534b4c0ca01fa', '2022-04-01 08:58:32', 0, 'https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif', NULL);
INSERT INTO `sys_role` (`id`, `name`, `code`, `note`, `status`, `who_created`, `when_created`, `who_modified`, `when_modified`, `app_id`) VALUES ('10d26189026a4dba86a8e63a4c717ed6', '超级管理员', 'admin', '应用超级管理员', 1, '', '2021-12-28 15:22:56', '056fb0eeb9a44cb0953534b4c0ca01fa', '2022-03-29 11:43:41', NULL);
INSERT INTO `sys_user_role` (`id`, `sys_user_id`, `sys_role_id`, `who_created`, `when_created`, `app_id`) VALUES ('b5f79a7cc794423e843a2b1fd9a27007', '056fb0eeb9a44cb0953534b4c0ca01fa', '10d26189026a4dba86a8e63a4c717ed6', '', '2022-03-10 06:31:39', NULL);
INSERT INTO `sys_menu` (`id`, `name`, `parent_id`, `icon`, `code`, `router_path`, `component_path`, `is_hidden`, `menu_type`, `api_codes`, `open_mode`, `keep_alive`, `path`, `order_num`, `status`, `who_created`, `when_created`, `who_modified`, `when_modified`, `app_id`, `data_type`, `theme`, `page_type`, `sidebar_nav_mode`, `top_nav_mode`, `main_mode`, `page_id`, `full_path`, `is_dev`) VALUES ('c2348bbf343a47b5852f12ee32869b13', '基础信息', NULL, 'documentation', 'system-info', 'sys/info', NULL, 0, 'M', '', 0, 1, '/c2348bbf343a47b5852f12ee32869b13/', 4, 1, '056fb0eeb9a44cb0953534b4c0ca01fa', '2021-12-30 11:11:11', '', '2022-01-10 19:02:36', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '/sys/info', 0);
INSERT INTO `sys_menu` (`id`, `name`, `parent_id`, `icon`, `code`, `router_path`, `component_path`, `is_hidden`, `menu_type`, `api_codes`, `open_mode`, `keep_alive`, `path`, `order_num`, `status`, `who_created`, `when_created`, `who_modified`, `when_modified`, `app_id`, `data_type`, `theme`, `page_type`, `sidebar_nav_mode`, `top_nav_mode`, `main_mode`, `page_id`, `full_path`, `is_dev`) VALUES ('1a246429b14e4db2be0e1847a3939e98', '菜单管理', '843af15ab7694d54af793e4a5e6fb76e', 'nested', 'menu', 'menu', '/sys/menu/index', 0, 'C', NULL, 0, 1, '/843af15ab7694d54af793e4a5e6fb76e/1a246429b14e4db2be0e1847a3939e98/', 5, 1, '056fb0eeb9a44cb0953534b4c0ca01fa', '2021-12-30 11:11:11', '', '2022-02-23 00:29:21', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '/sys/conf/menu', 0);
INSERT INTO `sys_menu` (`id`, `name`, `parent_id`, `icon`, `code`, `router_path`, `component_path`, `is_hidden`, `menu_type`, `api_codes`, `open_mode`, `keep_alive`, `path`, `order_num`, `status`, `who_created`, `when_created`, `who_modified`, `when_modified`, `app_id`, `data_type`, `theme`, `page_type`, `sidebar_nav_mode`, `top_nav_mode`, `main_mode`, `page_id`, `full_path`, `is_dev`) VALUES ('843af15ab7694d54af793e4a5e6fb76e', '系统配置', NULL, 'system', 'system-config', 'sys/conf', NULL, 0, 'M', NULL, 0, 1, '/843af15ab7694d54af793e4a5e6fb76e/', 5, 1, '056fb0eeb9a44cb0953534b4c0ca01fa', '2021-12-30 11:11:11', '', '2022-01-10 19:02:56', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '/sys/conf', 0);
INSERT INTO `sys_menu` (`id`, `name`, `parent_id`, `icon`, `code`, `router_path`, `component_path`, `is_hidden`, `menu_type`, `api_codes`, `open_mode`, `keep_alive`, `path`, `order_num`, `status`, `who_created`, `when_created`, `who_modified`, `when_modified`, `app_id`, `data_type`, `theme`, `page_type`, `sidebar_nav_mode`, `top_nav_mode`, `main_mode`, `page_id`, `full_path`, `is_dev`) VALUES ('58f5f98c57c74a91b6c2ca24c5df0ba9', '用户管理', 'c2348bbf343a47b5852f12ee32869b13', 'user', 'user', 'user/index', '/sys/user/index', 0, 'C', 'sys:user:list', 0, 1, '/c2348bbf343a47b5852f12ee32869b13/58f5f98c57c74a91b6c2ca24c5df0ba9/', 0, 1, '056fb0eeb9a44cb0953534b4c0ca01fa', '2021-12-30 11:11:11', '', '2022-02-23 00:28:46', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '/sys/info/user/index', 0);
INSERT INTO `sys_menu` (`id`, `name`, `parent_id`, `icon`, `code`, `router_path`, `component_path`, `is_hidden`, `menu_type`, `api_codes`, `open_mode`, `keep_alive`, `path`, `order_num`, `status`, `who_created`, `when_created`, `who_modified`, `when_modified`, `app_id`, `data_type`, `theme`, `page_type`, `sidebar_nav_mode`, `top_nav_mode`, `main_mode`, `page_id`, `full_path`, `is_dev`) VALUES ('611b9195b7ce4b3fb37f41023a907bda', '角色管理', 'c2348bbf343a47b5852f12ee32869b13', 'peoples', 'role', 'role/index', '/sys/role/index', 0, 'C', NULL, 0, 1, '/c2348bbf343a47b5852f12ee32869b13/611b9195b7ce4b3fb37f41023a907bda/', 2, 1, '056fb0eeb9a44cb0953534b4c0ca01fa', '2021-12-30 11:11:11', '', '2022-02-23 00:29:33', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '/sys/info/role/index', 0);
INSERT INTO `sys_menu` (`id`, `name`, `parent_id`, `icon`, `code`, `router_path`, `component_path`, `is_hidden`, `menu_type`, `api_codes`, `open_mode`, `keep_alive`, `path`, `order_num`, `status`, `who_created`, `when_created`, `who_modified`, `when_modified`, `app_id`, `data_type`, `theme`, `page_type`, `sidebar_nav_mode`, `top_nav_mode`, `main_mode`, `page_id`, `full_path`, `is_dev`) VALUES ('49d3319c02e542db9db32a6491193348', '字典管理', '843af15ab7694d54af793e4a5e6fb76e', 'dict', 'dictionary', 'dict/index', '/sys/dict/index', 0, 'C', NULL, 0, 1, '/843af15ab7694d54af793e4a5e6fb76e/49d3319c02e542db9db32a6491193348/', 0, 1, '056fb0eeb9a44cb0953534b4c0ca01fa', '2021-12-30 11:11:11', '', '2022-02-23 00:38:52', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '/sys/conf/dict/index', 0);
INSERT INTO `sys_menu` (`id`, `name`, `parent_id`, `icon`, `code`, `router_path`, `component_path`, `is_hidden`, `menu_type`, `api_codes`, `open_mode`, `keep_alive`, `path`, `order_num`, `status`, `who_created`, `when_created`, `who_modified`, `when_modified`, `app_id`, `data_type`, `theme`, `page_type`, `sidebar_nav_mode`, `top_nav_mode`, `main_mode`, `page_id`, `full_path`, `is_dev`) VALUES ('49d3319c02e542db9db32a6491193349', '字典数据', '843af15ab7694d54af793e4a5e6fb76e', '', 'dictionary-item', 'dict-item/index', '/sys/dictItem/index', 1, 'C', NULL, 0, 1, '/843af15ab7694d54af793e4a5e6fb76e/49d3319c02e542db9db32a6491193349/', 1, 1, '056fb0eeb9a44cb0953534b4c0ca01fa', '2021-12-30 11:11:11', '', '2021-12-30 15:32:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '/sys/conf/dict-item/index', 0);
INSERT INTO `sys_menu` (`id`, `name`, `parent_id`, `icon`, `code`, `router_path`, `component_path`, `is_hidden`, `menu_type`, `api_codes`, `open_mode`, `keep_alive`, `path`, `order_num`, `status`, `who_created`, `when_created`, `who_modified`, `when_modified`, `app_id`, `data_type`, `theme`, `page_type`, `sidebar_nav_mode`, `top_nav_mode`, `main_mode`, `page_id`, `full_path`, `is_dev`) VALUES ('a17e9c809f1049668633d8fe6103e740', '系统配置管理', '843af15ab7694d54af793e4a5e6fb76e', 'swagger', 'config', 'config', '/sys/config/index', 0, 'C', NULL, 0, 1, '/843af15ab7694d54af793e4a5e6fb76e/a17e9c809f1049668633d8fe6103e740/', 7, 1, '056fb0eeb9a44cb0953534b4c0ca01fa', '2021-12-30 11:11:11', '', '2022-02-23 00:41:11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '/sys/conf/config', 0);
INSERT INTO sys_dict (id, name, code, note, who_created, when_created, who_modified, when_modified, app_id) VALUES('27906b13c5c0484396e284a4368b24b3', '参数类型', 'sys_config_value_type', NULL, '', '2022-01-17 17:36:40', '', '2022-01-17 17:36:40', NULL);
INSERT INTO sys_dict_item (id, name, group_name, sys_dict_id, code, value, order_num, note, who_created, when_created, who_modified, when_modified, app_id) VALUES('53fa72c48f4c4324bd36733fe871b242', '文本', NULL, '27906b13c5c0484396e284a4368b24b3', 'sys_config_value_type', '0', 1, NULL, '', '2022-01-17 17:36:59', '', '2022-01-17 17:36:59', NULL);
INSERT INTO sys_dict_item (id, name, group_name, sys_dict_id, code, value, order_num, note, who_created, when_created, who_modified, when_modified, app_id) VALUES('98dba411055b460c913ab5454a6718c9', '图片', NULL, '27906b13c5c0484396e284a4368b24b3', 'sys_config_value_type', '1', 2, NULL, '', '2022-01-17 17:37:07', '', '2022-01-17 17:37:07', NULL);
INSERT INTO sys_dict_item (id, name, group_name, sys_dict_id, code, value, order_num, note, who_created, when_created, who_modified, when_modified, app_id) VALUES('a988ca46b6b445fc8f36d8b9d1243cb8', '颜色', NULL, '27906b13c5c0484396e284a4368b24b3', 'sys_config_value_type', '2', 3, NULL, '', '2022-01-17 17:37:15', '', '2022-01-17 17:37:15', NULL);

