# region server
server.servlet.context-path=/
server.port=18888
server.tomcat.accept-count=1000
server.tomcat.max-connections=10000
server.tomcat.threads.min-spare=100
server.tomcat.threads.max=800
# endregion server

# region pine server
pine.server.host=10.11.2.115
#  endregion pine server

# region spring
spring.jackson.date-format = yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.serialization.write-dates-as-timestamps=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=100MB
spring.servlet.multipart.max-request-size=1024MB
spring.servlet.multipart.max-file-size=512MB
spring.mvc.async.request-timeout=-1

# endregion spring

# region database
database.sources.db.databaseType=kdb
database.sources.db.channel=kdbHttp
database.sources.db.innerType=MySql
database.sources.db.server=http://10.11.2.215:8030
database.sources.db.executeSqlApi=/api/execute4debug
# DB??:?????:?????
database.sources.db.dbName=db:MySql:MySql,kingDB:KingDB:HSQLDB
# endregion database

# region encrypt
encrypt.mode=base64
# endregion encrypt

# region auth
app.ignore.urls=**/websocket;**/eiac
app.auth.enable=true
app.auth.iss=kingsware
app.auth.tokenExpireMinutes=120
app.auth.tokenSecret=3kj0ByucpznafmRd
app.auth.login-session-one=false
app.auth.mock-session-expire-minutes=300
app.auth.open-validate-code=true
# endregion auth

# region pine dev mode
app.mode.dev=true
# endregion pine dev mode

# region file
file.base-path=./upload

# region k-flow
app.k-flow.enable=true
# ???????FAAS????????????????????FAAS
app.file-local-to-faas=true
# endregion k-flow

# WaterPath
#file.WaterPath = ////192.168.106.113//
file.WaterPath = /Users/andyzheng/tmp/water
# schedule.QueueTask.cron
schedule.QueueTask.cron=0 0 10 * * ?
# schedule.WaterCheckBalanceTask.cron
schedule.WaterCheckBalanceTask.cron=0 0 10 * * ?
# endregion file
